version: '3'
services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot-local
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512M